const labels: Record<string, string> = {
  'header-sombra-divisoria': 'Divisor decorativo do cabeçalho',
  'menu-icone-crm-generico': 'Ícone do CRM imobiliário',
  'menu-icone-crm-urbano': 'Ícone do CRM Urbano',
  'menu-icone-crm-rural': 'Ícone do CRM Rural',
  'menu-icone-crm-temporada': 'Ícone do CRM para imóveis de temporada',
  'menu-icone-site-urbanas': 'Ícone do site para imobiliárias urbanas',
  'menu-icone-site-portais': 'Ícone do site para imobiliárias rurais',
  'menu-icone-site-loteadoras': 'Ícone do site para loteadoras',
  'menu-icone-apis-hub': 'Ícone de APIs e HUB integrador',
  'menu-icone-base-conhecimento': 'Ícone da base de conhecimento',
  'hero-decorativo-vetor-52': 'Vetor decorativo',
  'hero-decorativo-vetor-53': 'Vetor decorativo',
  'hero-decorativo-vetor-54': 'Vetor decorativo',
  'hero-destaque-confianca-contorno': 'Contorno decorativo do selo de confiança',
  'icone-mais-vendas-1': 'Ícone de mais vendas',
  'icone-mais-vendas-2': 'Ícone de mais vendas',
  'icone-mais-eficiencia-1': 'Ícone de mais eficiência',
  'icone-mais-eficiencia-2': 'Ícone de mais eficiência',
  'icone-imoveis-lancamentos': 'Ícone de imóveis em lançamento',
  'icone-imoveis-temporada': 'Ícone de imóveis de temporada',
  'icone-imoveis-rural': 'Ícone de imóveis rurais',
  'icone-imoveis-venda': 'Ícone de imóveis à venda',
  'icone-imoveis-locacao': 'Ícone de imóveis para locação',
  'divider-onda-decorativa': 'Onda decorativa',
  'icone-h3-funcionalidades-rurais': 'Ícone das funcionalidades rurais',
  'icone-h3-funcionalidades-temporada': 'Ícone das funcionalidades de temporada',
  'hero-website-onda-decorativa-branca': 'Onda decorativa branca',
  'hero-website-onda-decorativa-azul': 'Onda decorativa azul',
  'icone-site-imobiliarias-corretores': 'Ícone de imobiliárias e corretores',
  'icone-site-agrocorretores': 'Ícone de agrocorretores',
  'icone-site-loteadoras': 'Ícone de loteadoras',
  'icone-site-incorporadoras': 'Ícone de incorporadoras',
  'hero-crm-decoracao-pontos': 'Pontos decorativos',
  'hero-crm-decoracao-pontos-teal': 'Pontos decorativos verdes',
  'icone-crm-leads-chave': 'Ícone de leads',
  'icone-crm-relacionamento': 'Ícone de relacionamento com clientes',
  'icone-crm-perfil-performance': 'Ícone de perfil e performance',
  'icone-crm-integracoes': 'Ícone de integrações',
  'icone-imobiliarias-corretores': 'Ícone de imobiliárias e corretores',
  'icone-agrocorretores': 'Ícone de agrocorretores',
  'icone-loteadoras': 'Ícone de loteadoras',
  'icone-incorporadoras': 'Ícone de incorporadoras',
  'hero-depoimentos-onda-decorativa': 'Onda decorativa',
  'icone-estrelas-avaliacao': 'Avaliação 5 estrelas',
  'aspas-abertura': 'Aspas de abertura',
  'aspas-fechamento': 'Aspas de fechamento',
  'hero-faq-interrogacao-topo-esquerda': 'Ponto de interrogação decorativo',
  'hero-faq-interrogacao-inferior-esquerda-1': 'Ponto de interrogação decorativo',
  'hero-faq-interrogacao-inferior-esquerda-2': 'Ponto de interrogação decorativo',
  'hero-faq-interrogacao-superior-direita-1': 'Ponto de interrogação decorativo',
  'hero-faq-interrogacao-superior-direita-2': 'Ponto de interrogação decorativo',
  'hero-faq-interrogacao-caixa-esquerda': 'Caixa de interrogação decorativa',
  'hero-faq-interrogacao-caixa-direita': 'Caixa de interrogação decorativa',
  'icone-seta-faq': 'Seta para expandir a pergunta',
  'hero-pricing-bg-sol': 'Sol decorativo',
  'hero-pricing-bg-blob': 'Forma decorativa',
  'hero-pricing-bg-trator': 'Trator decorativo',
  'seta-lista-verde': 'Seta verde da lista',
  'hero-blog-onda-decorativa-branca': 'Onda decorativa branca',
  'hero-outros-produtos-onda-decorativa-branca': 'Onda decorativa branca',
  'social-facebook': 'Ícone do Facebook',
  'social-instagram': 'Ícone do Instagram',
  'social-linkedin': 'Ícone do LinkedIn',
  'social-blog': 'Ícone do blog da SUB100',
  'icone-modo-escuro': 'Ícone de modo escuro',
  'icone-coracao-footer': 'Ícone de coração',
  'legal-page-background': 'Fundo decorativo da página',
  'form-page-background': 'Fundo decorativo da página',
  'form-accent-rays-brand': 'Raios decorativos',
  'form-accent-rays-days': 'Raios decorativos',
  'form-accent-underline': 'Sublinhado decorativo',
  'legal-hero-ellipse': 'Elipse decorativa',
  'plano-e-preco-check-badge': 'Selo de item incluso',
  'faq-plus-circle': 'Ícone de mais para abrir a resposta',
  'faq-minus-circle': 'Ícone de menos para fechar a resposta',
  'eventos-icone-divider-horizontal': 'Divisor decorativo',
  'eventos-hero-shape-1': 'Forma decorativa',
  'eventos-hero-shape-2': 'Forma decorativa',
  'eventos-icone-play-triangle': 'Ícone de reproduzir',
  'eventos-icone-ellipse-1': 'Elipse decorativa',
  'eventos-icone-ellipse-2': 'Elipse decorativa',
  'eventos-icone-overview-play': 'Ícone de reproduzir vídeo',
  'crm-hero-icone-lancamentos-glyph': 'Ícone de lançamentos',
  'crm-hero-icone-venda': 'Ícone de venda',
  'crm-hero-icone-locacao-glyph': 'Ícone de locação',
  'crm-hero-icone-rural': 'Ícone de imóveis rurais',
  'crm-hero-icone-temporada-glyph': 'Ícone de temporada',
  'videos-hero-glow': 'Brilho decorativo',
  'videos-hero-curve-a': 'Curva decorativa',
  'crm-hero-seta-curva-verde': 'Seta curva decorativa',
  'videos-hero-globe': 'Ícone de globo',
  'videos-hero-people': 'Ícone de pessoas',
  'videos-hero-divider': 'Divisor decorativo',
  'featured-thumb': 'Miniatura do vídeo em destaque',
  'videos-play-featured-shadow': 'Sombra do botão de reproduzir',
  'videos-play-featured': 'Botão de reproduzir vídeo',
  'videos-play-featured-triangle': 'Ícone de reproduzir',
  'videos-play-demo': 'Botão de reproduzir demonstração',
  'videos-play-demo-triangle': 'Ícone de reproduzir',
  'videos-profile-1': 'Botão de reproduzir vídeo de perfil',
  'videos-profile-2': 'Botão de reproduzir vídeo de perfil',
  'videos-profile-3': 'Botão de reproduzir vídeo de perfil',
  'videos-profile-triangle': 'Ícone de reproduzir',
  'videos-cta-ellipse': 'Elipse decorativa',
  'form-calendar': 'Ícone de calendário',
  'form-settings': 'Ícone de configurações',
  'form-headphones': 'Ícone de suporte',
  'form-shield': 'Ícone de proteção de dados',
  'form-rocket-icon-bg': 'Ícone de foguete',
  'form-chevron-down': 'Seta para baixo',
  'form-arrow-right': 'Seta para a direita',
  'form-shield-check': 'Ícone de segurança',
  'form-building-trust': 'Ícone de imobiliárias',
  'form-lock': 'Ícone de privacidade',
  'form-monitor': 'Ícone de monitor',
  'form-user': 'Ícone de usuário',
  'form-message-circle-header': 'Ícone de mensagem',
  'obrigado': 'Astronauta em um foguete',
  'crm-hero-badge-icone': 'Ícone do CRM imobiliário',
  'crm-hero-ellipse-blur': 'Brilho decorativo',
  'card_arrow': 'Cartões flutuantes do módulo',
  'crm-hero-divider-onda': 'Onda decorativa',
  'crm-tecnologia-seta-curva': 'Seta curva decorativa',
  'crm-tecnologia-estrela': 'Estrela decorativa',
  'icone-crm-allinone-funil': 'Ícone de funil de vendas',
  'icone-crm-allinone-kanban': 'Ícone de kanban',
  'icone-crm-allinone-gestao-leads': 'Ícone de gestão de leads',
  'icone-crm-allinone-automacao-marketing': 'Ícone de automação de marketing',
  'icone-crm-allinone-agenda': 'Ícone de agenda',
  'icone-crm-allinone-relatorios': 'Ícone de relatórios',
  'icone-crm-overview-portfolio': 'Ícone de portfólio de imóveis',
  'icone-crm-overview-sincronizacao': 'Ícone de sincronização',
  'icone-crm-overview-leads': 'Ícone de leads',
  'crm-integrations-sub100-mark': 'Marca SUB100',
  'onda-decorativa-crm-depoimentos': 'Onda decorativa',
  'crm-urbano-hero-icone-calculadora': 'Ícone de calculadora',
  'crm-urbano-portfolio-icone-organizacao': 'Ícone de organização do portfólio',
  'crm-urbano-portfolio-icone-midias': 'Ícone de mídias do imóvel',
  'crm-urbano-portfolio-icone-proprietario': 'Ícone de proprietário',
  'crm-urbano-portfolio-icone-portais': 'Ícone de portais imobiliários',
  'crm-urbano-leads-bloco-blobs': 'Formas decorativas',
  'crm-urbano-leads-conectores-esquerda': 'Conectores decorativos',
  'crm-urbano-leads-pontos-esquerda': 'Pontos decorativos',
  'crm-urbano-leads-conectores-direita': 'Conectores decorativos',
  'crm-urbano-leads-pontos-direita': 'Pontos decorativos',
  'crm-urbano-leads-ponto-central': 'Ponto decorativo central',
  'crm-urbano-leads-icone-site': 'Ícone de site',
  'crm-urbano-leads-icone-portais': 'Ícone de portais imobiliários',
  'crm-urbano-leads-icone-whatsapp': 'Ícone do WhatsApp',
  'crm-urbano-leads-icone-redes-sociais': 'Ícone de redes sociais',
  'crm-urbano-leads-icone-indicacoes': 'Ícone de indicações',
  'crm-urbano-leads-icone-camadas': 'Ícone de camadas',
  'crm-urbano-leads-icone-tempo-1': 'Ícone de tempo',
  'crm-urbano-leads-icone-tempo-2': 'Ícone de tempo',
  'crm-urbano-leads-icone-tempo-3': 'Ícone de tempo',
  'crm-urbano-reports-icone-conversao': 'Ícone de conversão',
  'crm-urbano-reports-icone-tempo-resposta': 'Ícone de tempo de resposta',
  'crm-urbano-reports-icone-leads': 'Ícone de leads',
  'crm-urbano-reports-icone-metas': 'Ícone de metas',
  'crm-urbano-dashboard-ellipse-blur': 'Brilho decorativo',
  'crm-urbano-dashboard-icone-alertas': 'Ícone de alertas',
  'crm-urbano-dashboard-icone-indicadores': 'Ícone de indicadores',
  'crm-urbano-dashboard-icone-equipe': 'Ícone de equipe',
  'crm-urbano-modulos-icone-crm': 'Ícone do CRM imobiliário',
  'crm-urbano-modulos-icone-rural': 'Ícone do CRM Rural',
  'crm-urbano-modulos-icone-temporada': 'Ícone do CRM para imóveis de temporada',
  'crm-rural-hero-badge': 'Selo do CRM Rural',
  'crm-rural-hero-icone-rural': 'Ícone de imóveis rurais',
  'crm-rural-hero-divider-onda': 'Onda decorativa',
  'crm-rural-portfolio-icone-solo-bioma': 'Ícone de solo e bioma',
  'crm-rural-portfolio-icone-area': 'Ícone de área da propriedade',
  'crm-rural-portfolio-icone-pluviometria': 'Ícone de pluviometria',
  'crm-rural-portfolio-icone-integracao': 'Ícone de integração',
  'crm-rural-formal-closing-selo-assinado': 'Selo de contrato assinado',
  'crm-temporada-hero-icone-imovel': 'Ícone de imóvel',
  'crm-temporada-hero-calendar': 'Ícone de calendário',
  'crm-temporada-hero-divider-onda': 'Onda decorativa',
  'crm-temporada-portfolio-icone-calendario-reservas': 'Ícone de calendário de reservas',
  'crm-temporada-portfolio-icone-camera': 'Ícone de câmera',
  'crm-temporada-calendar-icone-gestao': 'Ícone de gestão de reservas',
  'crm-temporada-calendar-icone-status': 'Ícone de status da reserva',
  'crm-temporada-cta-arrow': 'Seta do botão',
  'icone-check-verde-circulo': 'Ícone de confirmado',
  'crm-temporada-financial-icone-olho': 'Ícone de visualização',
  'crm-temporada-financial-icone-sol': 'Ícone de sol',
  'crm-temporada-financial-icone-relogio': 'Ícone de relógio',
  'crm-temporada-inteligente-bg-lines': 'Linhas decorativas',
  'crm-temporada-inteligente-info-antes': 'Ícone de informações antes do SUBSEE',
  'crm-temporada-inteligente-info-depois': 'Ícone de informações depois do SUBSEE',
  'crm-temporada-inteligente-processos-antes': 'Ícone de processos antes do SUBSEE',
  'crm-temporada-inteligente-processos-depois': 'Ícone de processos depois do SUBSEE',
  'crm-temporada-inteligente-equipe-antes': 'Ícone de equipe antes do SUBSEE',
  'crm-temporada-inteligente-equipe-depois': 'Ícone de equipe depois do SUBSEE',
  'crm-temporada-inteligente-crescimento-antes': 'Ícone de crescimento antes do SUBSEE',
  'crm-temporada-inteligente-crescimento-depois': 'Ícone de crescimento depois do SUBSEE',
  'site-urbano-hero-icone-house': 'Ícone de casa',
  'site-urbano-ps-dormitorios': 'Ícone de dormitórios',
  'site-urbano-ps-banheiros': 'Ícone de banheiros',
  'site-urbano-ps-garagem': 'Ícone de garagem',
  'site-urbano-ps-area-privativa': 'Ícone de área privativa',
  'site-urbano-ps-area-total': 'Ícone de área total',
  'site-urbano-ps-face-imovel': 'Ícone de face do imóvel',
  'site-urbano-ps-posicao-quadra': 'Ícone de posição na quadra',
  'site-urbano-ps-visto': 'Ícone de imóvel visto',
  'site-urbano-ps-torres': 'Ícone de torres',
  'site-urbano-ps-andares': 'Ícone de andares',
  'site-urbano-ps-unidades': 'Ícone de unidades',
  'site-urbano-ps-pavimentos': 'Ícone de pavimentos',
  'site-urbano-ps-ano-construcao': 'Ícone de ano de construção',
  'site-urbano-ps-area-terreno': 'Ícone de área do terreno',
  'site-urbano-ps-ambientes': 'Ícone de ambientes',
  'site-urbano-internacional-seta': 'Seta decorativa',
  'internacional-google-icone': 'Ícone do Google',
  'site-urbano-internacional-seta-curva': 'Seta curva decorativa',
  'site-urbano-idioma-pt-br': 'Bandeira do Brasil, idioma português',
  'site-urbano-idioma-en': 'Bandeira dos Estados Unidos, idioma inglês',
  'site-urbano-idioma-es': 'Bandeira da Espanha, idioma espanhol',
  'site-urbano-idioma-de': 'Bandeira da Alemanha, idioma alemão',
  'site-urbano-idioma-it': 'Bandeira da Itália, idioma italiano',
  'site-urbano-idioma-zh': 'Bandeira da China, idioma chinês',
  'site-urbano-customization-icone-seo': 'Ícone de SEO',
  'site-urbano-customization-icone-organizacao': 'Ícone de organização do site',
  'site-urbano-customization-icone-banners': 'Ícone de banners',
  'site-urbano-customization-icone-institucional': 'Ícone de página institucional',
  'site-urbano-tools-seta-conector-1': 'Seta conectora',
  'site-urbano-tools-seta-conector-2': 'Seta conectora',
  'site-urbano-tools-icone-codigo': 'Ícone de código',
  'site-urbano-tools-icone-painel': 'Ícone de painel',
  'site-urbano-tools-icone-ativar': 'Ícone de ativar',
  'site-urbano-tools-check-status': 'Ícone de status ativo',
  'site-urbano-property-types-curva': 'Curva decorativa',
  'site-rural-hero-icone-modulo': 'Ícone do módulo de site rural',
  'site-rural-hero-icone-folha': 'Ícone de folha',
  'site-rural-listings-icone-descritivo': 'Ícone de memorial descritivo',
  'site-rural-listings-icone-mapas': 'Ícone de mapas',
  'site-rural-listings-icone-hidrica': 'Ícone de recursos hídricos',
  'site-rural-listings-icone-documentos': 'Ícone de documentos',
  'site-rural-pd-area-propriedade': 'Ícone de área da propriedade',
  'site-rural-pd-area-aberta': 'Ícone de área aberta',
  'site-rural-pd-periodo-chuvas': 'Ícone de período de chuvas',
  'site-rural-pd-aptidao-solo': 'Ícone de aptidão do solo',
  'site-rural-pd-bioma': 'Ícone de bioma',
  'site-rural-pd-utilizacao-solo': 'Ícone de utilização do solo',
  'site-rural-pd-altitude-media': 'Ícone de altitude média',
  'site-rural-pd-teor-argila': 'Ícone de teor de argila',
  'site-rural-pd-juquirada': 'Ícone de juquirada',
  'site-rural-pd-pluviometria': 'Ícone de pluviometria',
  'site-rural-customization-icone-seo': 'Ícone de SEO',
  'site-rural-customization-icone-organizacao': 'Ícone de organização do site',
  'site-rural-customization-icone-banners': 'Ícone de banners',
  'site-rural-customization-icone-institucional': 'Ícone de página institucional',
  'site-loteadoras-hero-icone-localizacao': 'Ícone de localização',
  'apis-hero': 'Ícone de APIs',
  'apis-hub-icone-integracao': 'Ícone de integração',
  'apis-hub-icone-sincronizacao': 'Ícone de sincronização',
  'apis-hub-icone-dados-centralizados': 'Ícone de dados centralizados',
  'apis-hub-icone-eficiencia': 'Ícone de eficiência',
  'apis-benefits-icone-sync': 'Ícone de sincronização',
  'apis-benefits-icone-integration': 'Ícone de integração',
  'apis-benefits-icone-shield': 'Ícone de segurança',
  'apis-other-modules-icone-base-conhecimento': 'Ícone da base de conhecimento',
  'base-conhecimento-icone-badge': 'Selo da base de conhecimento',
  'base-conhecimento-icone-suporte': 'Ícone de suporte',
  'base-conhecimento-icone-treinamentos-video': 'Ícone de treinamentos em vídeo',
  'base-conhecimento-icone-manuais': 'Ícone de manuais',
  'base-conhecimento-icone-eventos': 'Ícone de eventos',
  'base-conhecimento-icone-team': 'Ícone de equipe',
  'base-conhecimento-icone-training': 'Ícone de treinamento',
  'base-conhecimento-icone-satisfaction': 'Ícone de satisfação',
  'base-conhecimento-icone-award': 'Ícone de prêmio',
  'base-conhecimento-icone-shield-check': 'Ícone de segurança'
}

export function imageLabel(src?: string | null): string {
  const file = (src ?? '').split(/[?#]/)[0].split('/').pop() ?? ''
  const key = file.replace(/\.[a-z0-9]+$/i, '')
  const humanized = key.replace(/[-_]+/g, ' ').trim()
  return labels[key] ?? (humanized ? `Imagem ${humanized}` : 'Imagem do SUBSEE')
}
